name: CI
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
        - off
        - error
        - warn
        - info
        - debug
        - trace
      bmcd_version:
        description: 'BMC daemon version'
        required: false
        type: string

  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUST_LOG: ${{ inputs.logLevel }}

    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'true'

      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      
      - name: get version
        run: echo "BUILD_VERSION=`git describe --tags`" >> $GITHUB_ENV

      - name: install build host packages
        run: |
          sudo apt-get update &&\
          sudo apt-get install \
          build-essential \
          bc \
          subversion \
          git-core \
          libncurses5-dev \
          zlib1g-dev \
          gawk \
          flex \
          quilt \
          libssl-dev \
          xsltproc \
          libxml-parser-perl \
          mercurial \
          bzr \
          ecj \
          cvs \
          unzip \
          lib32z1 \
          lib32z1-dev \
          lib32stdc++6 \
          libstdc++6 \
          libncurses-dev \
          cpio \
          rsync \
          xxd -y

      - name: conditional bmcd version injection
        if: inputs.bmcd_version != ''
        run: |
         sed -ir 's#^BMCD_VERSION.*#BMCD_VERSION=${{ inputs.bmcd_version }}#g' ${{ github.workspace }}/tp2bmc/package/bmcd/bmcd.mk

      - name: configure
        run: |
          cd buildroot
          make BR2_EXTERNAL=../tp2bmc tp2bmc_defconfig

      - name: build all
        run: |
          cd buildroot
          make

      - name: stamp images
        run: |
          mkdir artifacts
          mv buildroot/output/images/tp2-bmc-firmware-sdcard.img artifacts/tp2-firmware-sdcard-${{ env.BUILD_VERSION }}.img
          mv buildroot/output/images/rootfs.erofs artifacts/tp2-ota-${{ env.BUILD_VERSION }}.tpu

      - name: archive artifacts
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error 
          name: tp2-${{ env.BUILD_VERSION }}
          path: artifacts/*

